### ISSUE TITLE
Error compiling with nightly: `thread 'rustc' panicked at compiler/rustc_mir_transform/src/validate.rs:152:26:`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1047]
Active toolchain:

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.83.0-nightly (7042c269c 2024-09-23)

```output
   Compiling axum-client-ip v0.6.0
thread 'rustc' panicked at compiler/rustc_mir_transform/src/validate.rs:152:26:
broken MIR in Item(DefId(0:339 ~ axum_server[2cd6]::tls_rustls::future::{impl#2}::poll)) (after phase change to runtime-optimized) at bb40[2]:
Normal edge to BasicBlockData { statements: [StorageDead(_56)], terminator: Some(Terminator { source_info: SourceInfo { span: /home/josecelano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-server-0.7.1/src/tls_rustls/future.rs:110:17: 110:18 (#0), scope: scope[1] }, kind: goto -> bb49 }), is_cleanup: false } violates unwind invariants (cleanup true -> false)
stack backtrace:
   0:     0x7f539488832a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haf9d4ce087fe74a0
   1:     0x7f5395003666 - core::fmt::write::h6d8d6eef4a4af1ac
   2:     0x7f5396125db3 - std::io::Write::write_fmt::h9c1a7b2c301e0052
   3:     0x7f5394888182 - std::sys::backtrace::BacktraceLock::print::h5a5be8b1e95a2bbb
   4:     0x7f539488a901 - std::panicking::default_hook::{{closure}}::ha72f3fa07467f26a
   5:     0x7f539488a734 - std::panicking::default_hook::hcc7760cf4378effc
   6:     0x7f539398286f - std[25b33fdea409b280]::panicking::update_hook::<alloc[1694921db2598cc8]::boxed::Box<rustc_driver_impl[91319f0e19a4d720]::install_ice_hook::{closure#0}>>::{closure#0}
   7:     0x7f539488b018 - std::panicking::rust_panic_with_hook::hfa739d875be2cf67
   8:     0x7f539488adea - std::panicking::begin_panic_handler::{{closure}}::h9a9134f6e05b41bd
   9:     0x7f53948887d9 - std::sys::backtrace::__rust_end_short_backtrace::h35fa4dfdd9fe9e0c
  10:     0x7f539488aaac - rust_begin_unwind
  11:     0x7f539209e7b0 - core::panicking::panic_fmt::hc3e7c6c5c469a97f
  12:     0x7f53926b311a - <rustc_mir_transform[2c59a960358d0625]::validate::Validator as rustc_mir_transform[2c59a960358d0625]::pass_manager::MirPass>::run_pass
  13:     0x7f539500dc64 - rustc_mir_transform[2c59a960358d0625]::pass_manager::run_passes_inner
  14:     0x7f5395a03922 - rustc_mir_transform[2c59a960358d0625]::optimized_mir
  15:     0x7f5395a021db - rustc_query_impl[16add4a89c515f02]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[16add4a89c515f02]::query_impl::optimized_mir::dynamic_query::{closure#2}::{closure#0}, rustc_middle[5962dfe9f3174182]::query::erase::Erased<[u8; 8usize]>>
  16:     0x7f5395031eae - rustc_query_system[cd92c81c02f5c019]::query::plumbing::try_execute_query::<rustc_query_impl[16add4a89c515f02]::DynamicConfig<rustc_query_system[cd92c81c02f5c019]::query::caches::DefIdCache<rustc_middle[5962dfe9f3174182]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[16add4a89c515f02]::plumbing::QueryCtxt, false>
  17:     0x7f539503145f - rustc_query_impl[16add4a89c515f02]::query_impl::optimized_mir::get_query_non_incr::__rust_end_short_backtrace
  18:     0x7f5395a0e963 - rustc_middle[5962dfe9f3174182]::query::plumbing::query_get_at::<rustc_query_system[cd92c81c02f5c019]::query::caches::DefIdCache<rustc_middle[5962dfe9f3174182]::query::erase::Erased<[u8; 8usize]>>>
  19:     0x7f5395a16305 - <rustc_metadata[bda71c6b2cfd99ea]::rmeta::encoder::EncodeContext>::encode_crate_root
  20:     0x7f53960b8ad3 - rustc_metadata[bda71c6b2cfd99ea]::rmeta::encoder::encode_metadata
  21:     0x7f53960c0f54 - rustc_metadata[bda71c6b2cfd99ea]::fs::encode_and_write_metadata
  22:     0x7f53960bfd43 - <rustc_interface[1294e3f809d58823]::queries::Linker>::codegen_and_build_linker
  23:     0x7f5395d2a34b - rustc_interface[1294e3f809d58823]::interface::run_compiler::<core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>, rustc_driver_impl[91319f0e19a4d720]::run_compiler::{closure#0}>::{closure#1}
  24:     0x7f5395dbf210 - std[25b33fdea409b280]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[1294e3f809d58823]::util::run_in_thread_with_globals<rustc_interface[1294e3f809d58823]::util::run_in_thread_pool_with_globals<rustc_interface[1294e3f809d58823]::interface::run_compiler<core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>, rustc_driver_impl[91319f0e19a4d720]::run_compiler::{closure#0}>::{closure#1}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#0}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>
  25:     0x7f5395dbf87a - <<std[25b33fdea409b280]::thread::Builder>::spawn_unchecked_<rustc_interface[1294e3f809d58823]::util::run_in_thread_with_globals<rustc_interface[1294e3f809d58823]::util::run_in_thread_pool_with_globals<rustc_interface[1294e3f809d58823]::interface::run_compiler<core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>, rustc_driver_impl[91319f0e19a4d720]::run_compiler::{closure#0}>::{closure#1}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#0}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[1e18fbba9f4dcc19]::result::Result<(), rustc_span[d14b83658cea8543]::ErrorGuaranteed>>::{closure#1} as core[1e18fbba9f4dcc19]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7f5395dbfc6b - std::sys::pal::unix::thread::Thread::new::thread_start::h9c0c387d4b02e16a
  27:     0x7f539008f18a - start_thread
                               at ./nptl/pthread_create.c:444:8
  28:     0x7f539011dbd0 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  29:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/josecelano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-server-0.7.1/rustc-ice-2024-09-24T10_31_42-960904.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=1 -C linker-plugin-lto -C debuginfo=1 -C debug-assertions=on

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `tls_rustls::future::<impl at /home/josecelano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-server-0.7.1/src/tls_rustls/future.rs:61:1: 64:39>::poll`
end of query stack
error: could not compile `axum-server` (lib)

Caused by:
  process didn't exit successfully: `/home/josecelano/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name axum_server --edition=2021 /home/josecelano/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-server-0.7.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=142 --crate-type lib --emit=dep-info,metadata,link -C opt-level=1 -C linker-plugin-lto -C debuginfo=1 -C debug-assertions=on --cfg 'feature="arc-swap"' --cfg 'feature="default"' --cfg 'feature="rustls"' --cfg 'feature="rustls-pemfile"' --cfg 'feature="rustls-pki-types"' --cfg 'feature="tls-rustls"' --cfg 'feature="tls-rustls-no-provider"' --cfg 'feature="tokio-rustls"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("arc-swap", "default", "openssl", "rustls", "rustls-pemfile", "rustls-pki-types", "tls-openssl", "tls-rustls", "tls-rustls-no-provider", "tokio-openssl", "tokio-rustls"))' -C metadata=44b58cdf5cf1a961 -C extra-filename=-44b58cdf5cf1a961 --out-dir /home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps -L dependency=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps --extern arc_swap=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libarc_swap-edfc3c5153f9ceee.rmeta --extern bytes=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libbytes-3e70d2f5d72f8366.rmeta --extern futures_util=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libfutures_util-3e2055003b63f4fa.rmeta --extern http=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libhttp-ece7a43e42e37f9d.rmeta --extern http_body=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libhttp_body-e3ca6c808f5d13c2.rmeta --extern http_body_util=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libhttp_body_util-30175f29fb07b886.rmeta --extern hyper=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libhyper-f86fc45d1243496c.rmeta --extern hyper_util=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libhyper_util-cf02676e9f2d9394.rmeta --extern pin_project_lite=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libpin_project_lite-c947acc61653d80a.rmeta --extern rustls=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/librustls-2dc024b91c9ef017.rmeta --extern rustls_pemfile=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/librustls_pemfile-6304fccae70b7d07.rmeta --extern rustls_pki_types=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/librustls_pki_types-63a275f885323331.rmeta --extern tokio=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libtokio-23ef45f6b28a6ec3.rmeta --extern tokio_rustls=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libtokio_rustls-5cc304a930236692.rmeta --extern tower=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libtower-d4fcf46851999fc4.rmeta --extern tower_service=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/deps/libtower_service-04a1a20c383d1452.rmeta --cap-lints allow -D warnings -D future-incompatible -D let-underscore -D nonstandard-style -D rust-2018-compatibility -D rust-2018-idioms -D rust-2021-compatibility -D unused -L native=/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/target/debug/build/aws-lc-sys-5f21e218fca33242/out` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

It works with the stable:

stable-x86_64-unknown-linux-gnu (default)
rustc 1.81.0 (eeb90cda1 2024-09-04)

**Comment by josecelano** [comment]
It's working now with:

```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.84.0-nightly (ee612c45f 2024-11-19)
```
