### ISSUE TITLE
Tracker won't start : Errors while processing config: TrackerModeIncompatible.

### ISSUE THREAD

**Issue by iloveyourwife** [torrust/torrust-tracker#43]
I've an error when starting tracker : 

```
thread 'main' panicked at 'Errors while processing config: TrackerModeIncompatible.', src/main.rs:14:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
   3: torrust_tracker::main::{{closure}}
   4: torrust_tracker::main
```

Here is my config file :

```
log_level = "info"
mode = "private_listed"
db_path = "data.db"
persistence = true
cleanup_interval = 600
cleanup_peerless = false
external_ip = "0.0.0.0"
announce_interval = 120
announce_interval_min = 120
peer_timeout = 900
on_reverse_proxy = true

[[http_trackers]]
enabled = true
bind_address = "0.0.0.0:6969"
ssl_enabled = false
ssl_bind_address = "0.0.0.0:6868"
ssl_cert_path = ""
ssl_key_path = ""

[[udp_trackers]]
enabled = false
bind_address = "0.0.0.0:6969"

[http_api]
enabled = true
bind_address = "10.8.0.40:1212"

[http_api.access_tokens]
admin = "xxxxxxxxxxxxxx"
```

**Comment by mickvandijke** [comment]
Sorry for this, we made a mistake in the config code, that basically does not allow the tracker to run in private mode. Your config is correct.

I will push a new release of the tracker later today that fixes this and many other bugs/performance issues.

**Comment by mickvandijke** [comment]
New release (v2.3.0) is now available.
