### ISSUE TITLE
Can't use the merge script because of the new ruleset

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#492]
Hi @da2ce7,

I can't use anymore the [Bitcoin merge script](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/github-merge.py) to merge pull requests because of the new ruleset for branches. Because we cannot push directly to the `develop` branch. Should members with permission to merge add an exception to the rule? Or should we stop using that script?

**Comment by da2ce7** [comment]
I've been using the merge script successfully with pull requests and the current ruleset.

**Comment by josecelano** [comment]
> I've been using the merge script successfully with pull requests and the current ruleset.

Ok, I'll check it again.

**Comment by josecelano** [comment]
For the Index and Index-GUI, it is working. Maybe the ruleset was not the problem. I'm closing it, and I will open it again if I can confirm and reproduce it.

**Comment by josecelano** [comment]
Hi @da2ce7 @mario-nt

I have this problem trying to merge the PR https://github.com/torrust/torrust-index/pull/365 on the Index.

The problem is the commit is not signed.

```console
$ gh-merge 365
torrust/torrust-index#365 chore: updated cargo dependency toml to 0.8.6 into develop
* 0871ebef0b992c92f0831d62829b01958dbae930 chore: updated cargo dependency toml to 0.8.6 (MMelchor) (mario/update-dependencies-toml-0.8.6, pull/365/head)

Dropping you on a shell so you can try building/testing the merged source.
Run 'git diff HEAD~' to show the changes being merged.
Type 'exit' when done.
(365)josecelano@josecelano-desktop:~/Documents/git/committer/me/github/torrust/torrust-index$ exit
exit
[pull/365/local-merge e12b50a] Merge torrust/torrust-index#365: chore: updated cargo dependency toml to 0.8.6
 Date: Tue Oct 31 09:40:20 2023 +0000
torrust/torrust-index#365 chore: updated cargo dependency toml to 0.8.6 into develop
* 0871ebef0b992c92f0831d62829b01958dbae930 chore: updated cargo dependency toml to 0.8.6 (MMelchor) (mario/update-dependencies-toml-0.8.6, pull/365/head)
Top commit has no ACKs!
Type 's' to sign off on the above merge, or 'x' to reject and exit. s

Type 'push' to push the result to git@github.com:torrust/torrust-index, branch develop, or 'x' to exit without pushing. push

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 32 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (4/4), 1.49 KiB | 1.49 MiB/s, done.
Total 4 (delta 2), reused 3 (delta 2), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH013: Repository rule violations found for refs/heads/develop.
remote: Review all repository rules at http://github.com/torrust/torrust-index/rules?ref=refs%2Fheads%2Fdevelop
remote: 
remote: - Commits must have valid signatures.
remote: 
To github.com:torrust/torrust-index
 ! [remote rejected] develop -> develop (push declined due to repository rule violations)
error: failed to push some refs to 'github.com:torrust/torrust-index'
Traceback (most recent call last):
  File "/home/josecelano/bin/github-merge.py", line 484, in <module>
    main()
  File "/home/josecelano/bin/github-merge.py", line 476, in main
    subprocess.check_call([GIT,'push',host_repo,'refs/heads/'+branch])
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'git@github.com:torrust/torrust-index', 'refs/heads/develop']' returned non-zero exit status 1.

```
