### ISSUE TITLE
Application should abort is one of the services can't be run due to invalid configuration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#618]
For example:

- If you try to use a port that's being used.
- If you try to use TLS for a service (API or HTTP tracker) but something is missing in the configuration.

**Comment by josecelano** [comment]
This seems to be already fixed.

If I run one instance with alls services enabled and then try to run a second instance the application panics.


```josecelano@josecelano-desktop:~/Documents/git/committer/me/github/torrust/torrust-tracker$ cargo run
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.07s
     Running `target/debug/torrust-tracker`
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-03-14T13:04:21.612365042+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
thread 'tokio-runtime-worker' panicked at src/servers/udp/server.rs:244:62:
Could not bind to {self.socket}.: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/src/servers/udp/server.rs:132:38:
it should be able to start the service: RecvError(())
thread 'tokio-runtime-worker' panicked at src/servers/registar.rs:89:14:
it should receive the service registration from the started service: RecvError(())
josecelano@josecelano-desktop:~/Documents/git/committer/me/github/torrust/torrust-tracker$ cargo run
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.07s
     Running `target/debug/torrust-tracker`
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-03-14T13:05:07.237630799+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-03-14T13:05:07.238191795+00:00 [torrust_tracker::bootstrap::jobs][INFO] TLS not enabled
thread 'tokio-runtime-worker' panicked at src/servers/http/server.rs:43:64:
Could not bind tcp_listener to address.: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/src/servers/http/server.rs:162:38:
it should be able to start the service: RecvError(())
thread 'tokio-runtime-worker' panicked at src/servers/registar.rs:89:14:
it should receive the service registration from the started service: RecvError(())
josecelano@josecelano-desktop:~/Documents/git/committer/me/github/torrust/torrust-tracker$ cargo run
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.08s
     Running `target/debug/torrust-tracker`
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-03-14T13:05:18.582864890+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-03-14T13:05:18.583443526+00:00 [torrust_tracker::bootstrap::jobs][INFO] TLS not enabled
thread 'tokio-runtime-worker' panicked at src/servers/apis/server.rs:219:64:
Could not bind tcp_listener to address.: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-03-14T13:05:18.583599895+00:00 [torrust_tracker::servers::apis::server][ERROR] Unable to start API server: channel closed
thread 'main' panicked at /home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/src/servers/apis/server.rs:144:17:
Unable to start API server: channel closed
thread 'tokio-runtime-worker' panicked at src/servers/registar.rs:89:14:
it should receive the service registration from the started service: RecvError(())
josecelano@josecelano-desktop:~/Documents/git/committer/me/github/torrust/torrust-tracker$ cargo run
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.08s
     Running `target/debug/torrust-tracker`
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-03-14T13:05:31.319003407+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-03-14T13:05:31.319636022+00:00 [HEALTH CHECK API][INFO] Starting on: http://127.0.0.1:1313
thread 'tokio-runtime-worker' panicked at src/servers/health_check_api/server.rs:79:55:
Could not bind tcp_listener to address.: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/src/bootstrap/jobs/health_check_api.rs:62:19:
the Health Check API server was dropped: channel closed
```

I've also tried to run a service enabling TLS but with the missing certificate and key paths.

```
josecelano@josecelano-desktop:~/Documents/git/committer/me/github/torrust/torrust-tracker$ cargo run
    Finished `dev` profile [optimized + debuginfo] target(s) in 0.09s
     Running `target/debug/torrust-tracker`
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-03-14T13:15:38.103903177+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
thread 'main' panicked at /home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/src/bootstrap/jobs/tracker_apis.rs:71:28:
it should have a valid tracker api tls configuration: MissingTlsConfig { location: Location { file: "/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker/src/bootstrap/jobs/mod.rs", line: 42, col: 23 } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/servers/registar.rs:89:14:

it should receive the service registration from the started service: RecvError(())
```
