### ISSUE TITLE
Panic running tracker after merging PR

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#626]
Hi @da2ce7 after merging this [PR](https://github.com/torrust/torrust-tracker/pull/623) we have again problems running the services:

UDP tracker:

```console
$ cargo run
    Finished dev [optimized + debuginfo] target(s) in 0.07s
     Running `target/debug/torrust-tracker`
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-01-17T15:42:22.916667054+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-01-17T15:42:22.917287900+00:00 [UDP Tracker][INFO] Starting on: udp://0.0.0.0:6969
2024-01-17T15:42:22.917301780+00:00 [UDP Tracker][INFO] Started on: udp://0.0.0.0:6969
2024-01-17T15:42:22.917314150+00:00 [torrust_tracker::bootstrap::jobs::http_tracker][INFO] Note: Not loading Http Tracker Service, Not Enabled in Configuration.
2024-01-17T15:42:22.917325980+00:00 [Health Check API][INFO] Starting on: http://127.0.0.1:1313
thread 'tokio-runtime-worker' panicked at src/servers/registar.rs:84:32:
it should receive the listing: RecvError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-01-17T15:42:22.917372540+00:00 [Health Check API][INFO] Started on: http://127.0.0.1:1313
thread 'tokio-runtime-worker' panicked at src/servers/signals.rs:52:25:
Failed to install stop signal: channel closed
```

HTTP tracker:

```console
$ cargo run
    Finished dev [optimized + debuginfo] target(s) in 0.08s
     Running `target/debug/torrust-tracker`
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-01-17T15:44:25.861291618+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-01-17T15:44:25.861885065+00:00 [torrust_tracker::bootstrap::jobs][INFO] TLS not enabled
2024-01-17T15:44:25.861960704+00:00 [HTTP Tracker][INFO] Starting on: http://0.0.0.0:38039
2024-01-17T15:44:25.861974164+00:00 [HTTP Tracker][INFO] Started on: http://0.0.0.0:38039
2024-01-17T15:44:25.861994784+00:00 [Health Check API][INFO] Starting on: http://127.0.0.1:1313
2024-01-17T15:44:25.862057804+00:00 [Health Check API][INFO] Started on: http://127.0.0.1:1313
thread 'tokio-runtime-worker' panicked at src/servers/signals.rs:52:25:
Failed to install stop signal: channel closed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

API:

```console
$ cargo run
    Finished dev [optimized + debuginfo] target(s) in 0.07s
     Running `target/debug/torrust-tracker`
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-01-17T15:45:48.496410648+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-01-17T15:45:48.497012334+00:00 [torrust_tracker::bootstrap::jobs::http_tracker][INFO] Note: Not loading Http Tracker Service, Not Enabled in Configuration.
2024-01-17T15:45:48.497018514+00:00 [torrust_tracker::bootstrap::jobs][INFO] TLS not enabled
thread 'tokio-runtime-worker' panicked at src/servers/registar.rs:84:32:
it should receive the listing: RecvError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-01-17T15:45:48.497135114+00:00 [API][INFO] Starting on http://127.0.0.1:45317
2024-01-17T15:45:48.497164673+00:00 [API][INFO] Started on http://127.0.0.1:45317
2024-01-17T15:45:48.497182813+00:00 [Health Check API][INFO] Starting on: http://127.0.0.1:1313
2024-01-17T15:45:48.497223463+00:00 [Health Check API][INFO] Started on: http://127.0.0.1:1313
thread 'tokio-runtime-worker' panicked at src/servers/signals.rs:52:25:
Failed to install stop signal: channel closed
```

Health Check API

```console
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-01-19T12:55:30.920929819+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-01-19T12:55:30.921525496+00:00 [Health Check API][INFO] Starting on: http://127.0.0.1:1313
2024-01-19T12:55:30.921596876+00:00 [Health Check API][INFO] Started on: http://127.0.0.1:1313
thread 'tokio-runtime-worker' panicked at src/servers/signals.rs:52:25:
Failed to install stop signal: channel closed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And you can not stop the UDP and HTTP trackers with CTRL+C.

Besides, for the API, it keeps waiting even if there are no more alive connections (this is an old behavior):

```console
!! shuting down in 90 seconds !!
2024-01-17T15:46:31.493528347+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:32.494658160+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:33.495743842+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:34.496885293+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:35.498263527+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:36.499403840+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:37.500433804+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:38.501785104+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:39.502845177+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:40.503956871+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
2024-01-17T15:46:41.505213133+00:00 [torrust_tracker::servers::signals][INFO] remaining alive connections: 0
```

**Comment by josecelano** [comment]
Relates to:

- https://github.com/torrust/torrust-tracker/pull/589
- https://github.com/torrust/torrust-tracker/pull/593
- https://github.com/torrust/torrust-tracker/pull/595

**Comment by josecelano** [comment]
I've started with the API. It's strange because the test pass:

```console
$ ct it_should_be_able_to_start_and_stop -- --nocapture
   Compiling torrust-tracker v3.0.0-alpha.12-develop (/home/josecelano/Documents/git/committer/me/github/torrust/torrust-tracker)
    Finished test [optimized + debuginfo] target(s) in 17.31s
     Running unittests src/lib.rs (target/debug/deps/torrust_tracker-6f9648c253b029aa)

running 3 tests
2024-01-18T16:26:25.269680784+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-01-18T16:26:25.282833759+00:00 [torrust_tracker::bootstrap::jobs][INFO] TLS not enabled
2024-01-18T16:26:25.282945138+00:00 [API][INFO] Starting on http://127.0.0.1:33093
2024-01-18T16:26:25.282948258+00:00 [API][INFO] Started on http://127.0.0.1:33093
2024-01-18T16:26:25.282979408+00:00 [torrust_tracker::servers::signals][INFO] Halt signal processed: Normal
2024-01-18T16:26:25.282982118+00:00 [torrust_tracker::servers::signals][INFO] Shutting down tracker API server on socket address: 127.0.0.1:33093
2024-01-18T16:26:25.282983438+00:00 [torrust_tracker::servers::signals][INFO] Sending graceful shutdown signal
!! shuting down in 90 seconds !!
test servers::apis::server::tests::it_should_be_able_to_start_and_stop ... ok
2024-01-18T16:26:25.283181617+00:00 [torrust_tracker::bootstrap::jobs][INFO] TLS not enabled
2024-01-18T16:26:25.283185547+00:00 [UDP Tracker][DEBUG] Launcher starting ...
2024-01-18T16:26:25.283222136+00:00 [HTTP Tracker][INFO] Starting on: http://127.0.0.1:34193
2024-01-18T16:26:25.283223816+00:00 [UDP Tracker][INFO] Starting on: udp://127.0.0.1:43945
2024-01-18T16:26:25.283225506+00:00 [HTTP Tracker][INFO] Started on: http://127.0.0.1:34193
2024-01-18T16:26:25.283232506+00:00 [UDP Tracker][INFO] Started on: udp://127.0.0.1:43945
2024-01-18T16:26:25.283245426+00:00 [torrust_tracker::servers::signals][INFO] Halt signal processed: Normal
2024-01-18T16:26:25.283246956+00:00 [UDP Tracker][DEBUG] Waiting for packets on socket address: udp://127.0.0.1:43945 ...
2024-01-18T16:26:25.283248506+00:00 [torrust_tracker::servers::signals][INFO] Shutting down HTTP server on socket address: 127.0.0.1:34193
2024-01-18T16:26:25.283259136+00:00 [torrust_tracker::servers::signals][INFO] Sending graceful shutdown signal
!! shuting down in 90 seconds !!
2024-01-18T16:26:25.283255166+00:00 [UDP Tracker][DEBUG] Waiting for halt signal for socket address: udp://127.0.0.1:43945  ...
2024-01-18T16:26:25.283276946+00:00 [torrust_tracker::servers::signals][INFO] Halt signal processed: Normal
2024-01-18T16:26:25.283279286+00:00 [torrust_tracker::servers::signals][INFO] Shutting down UDP server on socket address: udp://127.0.0.1:43945
2024-01-18T16:26:25.283282476+00:00 [UDP Tracker][DEBUG] Halt signal spawned task stopped on address: udp://127.0.0.1:43945
test servers::http::server::tests::it_should_be_able_to_start_and_stop ... ok
test servers::udp::server::tests::it_should_be_able_to_start_and_stop ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 268 filtered out; finished in 0.01s

     Running unittests src/bin/http_health_check.rs (target/debug/deps/http_health_check-224e15826d29b9c8)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/bin/http_tracker_client.rs (target/debug/deps/http_tracker_client-ffb2e714188d5b05)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/torrust_tracker-a3f39e9c7d2ecb8f)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/integration.rs (target/debug/deps/integration-e0dd648e2b9f1174)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 106 filtered out; finished in 0.00s
```

**Comment by josecelano** [comment]
But the test starts and immediately stops. In the real app, we have to wait for the service to finish, so it's normal that is working on the tests but not in production.

The problem could be the same one as I fixed in the previous version. We are waiting for the wrong spawned task to finish. We have to wait for the task running the service.

**Comment by josecelano** [comment]
In the end the error: `Failed to install stop signal: channel closed` was produced only by the Health Check API.
